"use client";

import { useEffect, useState } from "react";
import Badge from "@/components/ui/Badge";
import Card from "@/components/ui/Card";

/**
 * The Exports tab on the deliverability dashboard: the log of every
 * spreadsheet the site has generated.
 *
 * ONE-SHOT LIST, no realtime listener. `dataExports` is shut to every client
 * in firestore.rules (an audit its own actor can amend is not an audit), so
 * the rows arrive through GET /api/admin/deliverability/exports on the Admin
 * SDK. The dashboard's Refresh button re-mounts the load via `reloadKey`,
 * which is all this needs: rows appear when somebody downloads a file, which
 * is a thing an admin does, not a thing that happens to them.
 *
 * The export routes that WRITE these rows land later (the applications export
 * in PR34, the register and roster exports in PR45). Until then the table is
 * correctly empty, and its empty state says so rather than implying something
 * is broken.
 *
 * The copy says "downloads generated by the site are recorded". Not "every
 * export is logged": a reviewer's queue already renders the whole
 * applications payload in their browser, so copy and paste is outside this
 * log by construction, and the privacy policy is worded to match. Do not
 * upgrade the sentence.
 */

type ExportRow = {
  id: string;
  kind: string;
  kindLabel: string;
  kindKnown: boolean;
  actorUid: string;
  actorName: string;
  scope: Record<string, string>;
  rowCount: number;
  filename: string;
  at: string | null;
  viaImpersonation: boolean;
};

const NOT_RECORDED = "Not recorded";

function formatDate(iso: string | null): string {
  if (!iso) return NOT_RECORDED;
  try {
    return new Date(iso).toLocaleString(undefined, {
      day: "numeric",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return iso;
  }
}

/**
 * The scope map as one readable line, in the order a reader scans it.
 *
 * EVERY key of `DataExportScope` must have a line here, and a new scope key
 * that does not get one is a bug rather than a cosmetic gap: the fallback is
 * "Whole site", so an export of a single circulation's answers would be
 * displayed as an export of everything. A row that overstates what a file
 * covered is worse than a blank cell, because this log is the only control
 * that survives the file leaving the platform. tests/data-exports.test.mjs
 * pins the two lists against each other so the next key cannot be forgotten.
 */
function formatScope(scope: Record<string, string>): string {
  const parts: string[] = [];
  if (scope.roundId) parts.push(`Round ${scope.roundId}`);
  if (scope.runId) parts.push(`Run ${scope.runId}`);
  if (scope.groupId) parts.push(`Group ${scope.groupId}`);
  if (scope.periodId) parts.push(`Membership ${scope.periodId}`);
  if (scope.circulationId) parts.push(`Circulation ${scope.circulationId}`);
  return parts.length > 0 ? parts.join(" · ") : "Whole site";
}

export default function DeliverabilityExports({
  reloadKey = 0,
}: {
  /** Bumped by the dashboard's Refresh button to re-run the load. */
  reloadKey?: number;
}) {
  const [rows, setRows] = useState<ExportRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      // Inside the async body rather than in the effect itself: a synchronous
      // setState in an effect triggers a cascading render, which the lint
      // rule catches and which buys nothing here.
      setLoading(true);
      try {
        const res = await fetch("/api/admin/deliverability/exports");
        if (!res.ok) throw new Error(`Exports fetch ${res.status}`);
        const body = (await res.json()) as { items: ExportRow[] };
        if (cancelled) return;
        setRows(body.items ?? []);
        setError(null);
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : "Failed to load");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [reloadKey]);

  return (
    <section style={{ display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
      <h3 style={{ fontSize: "var(--text-lg)" }}>Exports</h3>
      <p
        style={{
          margin: 0,
          fontSize: "var(--text-sm)",
          color: "var(--color-text-muted)",
        }}
      >
        Downloads generated by the site are recorded here: registers, rosters,
        applications and membership lists. A row is written before the file is
        handed over, and an export is refused if the row cannot be written.
        This does not cover somebody copying what is already on their screen.
      </p>

      {error && (
        <Card padding="md">
          <p style={{ color: "var(--color-danger)", margin: 0 }}>{error}</p>
        </Card>
      )}

      {loading && rows.length === 0 ? (
        <Card padding="md">
          <p style={{ color: "var(--color-text-muted)", margin: 0 }}>Loading…</p>
        </Card>
      ) : rows.length === 0 ? (
        // Only when the load SUCCEEDED and came back empty. A failed fetch
        // also leaves `rows` empty, and rendering "no exports recorded yet"
        // under the error card would answer a question the request never
        // got to ask: it reads as "nobody has ever downloaded anything",
        // which is the opposite of what a failure means on an audit log.
        // On an error the card above is the whole answer.
        error ? null : (
          <Card padding="md">
            <p style={{ color: "var(--color-text-muted)", margin: 0 }}>
              No exports recorded yet. Rows appear here the first time anyone
              downloads a register, a roster, an applications table or a
              membership list.
            </p>
          </Card>
        )
      ) : (
        <Card padding="sm">
          <div style={{ overflowX: "auto" }}>
            <table
              style={{
                width: "100%",
                borderCollapse: "collapse",
                fontSize: "var(--text-sm)",
              }}
            >
              <thead>
                <tr style={{ textAlign: "left", color: "var(--color-text-muted)" }}>
                  <th style={{ padding: "var(--space-2)", fontWeight: 500 }}>What</th>
                  <th style={{ padding: "var(--space-2)", fontWeight: 500 }}>Who</th>
                  <th style={{ padding: "var(--space-2)", fontWeight: 500 }}>Scope</th>
                  <th style={{ padding: "var(--space-2)", fontWeight: 500 }}>People</th>
                  <th style={{ padding: "var(--space-2)", fontWeight: 500 }}>File</th>
                  <th style={{ padding: "var(--space-2)", fontWeight: 500 }}>When</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((row) => (
                  <tr key={row.id} style={{ borderTop: "1px solid var(--color-border)" }}>
                    <td style={{ padding: "var(--space-2)" }}>
                      <Badge tone="neutral">{row.kindLabel}</Badge>
                      {!row.kindKnown && row.kind !== "" && (
                        <span
                          style={{
                            marginLeft: "var(--space-2)",
                            color: "var(--color-text-muted)",
                          }}
                        >
                          {row.kind}
                        </span>
                      )}
                    </td>
                    <td style={{ padding: "var(--space-2)" }}>
                      {row.actorName || row.actorUid || NOT_RECORDED}
                      {row.viaImpersonation && (
                        <>
                          {" "}
                          <Badge tone="warning">In a view-as session</Badge>
                        </>
                      )}
                    </td>
                    <td
                      style={{
                        padding: "var(--space-2)",
                        color: "var(--color-text-muted)",
                        wordBreak: "break-all",
                      }}
                    >
                      {formatScope(row.scope)}
                    </td>
                    <td style={{ padding: "var(--space-2)", whiteSpace: "nowrap" }}>
                      {row.rowCount}
                    </td>
                    <td style={{ padding: "var(--space-2)", wordBreak: "break-all" }}>
                      {row.filename || NOT_RECORDED}
                    </td>
                    <td style={{ padding: "var(--space-2)", whiteSpace: "nowrap" }}>
                      {formatDate(row.at)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}
    </section>
  );
}
