import { Link, Text } from "@react-email/components";
import EmailChrome, { emailFooterTextStyle, emailLinkStyle } from "./EmailChrome";
import { channelLabel } from "@/lib/firestore/subscriptions";

type Props = {
  /** Active channels for this email after the confirmation just landed. */
  channels: string[];
  /**
   * One unsub URL per channel. Each url is a signed token scoped to that
   * channel; clicking it flips just that one row to `unsubscribed`.
   */
  unsubUrls: Record<string, string>;
  /**
   * Optional "unsubscribe from everything" url (token with `c: "all"`),
   * for the very bottom of the footer. Generated by the confirm route.
   */
  unsubAllUrl?: string;
  /** Optional first / preferred name. When present, used in the greeting. */
  name?: string;
};

/**
 * Sent after the subscriber clicks the confirmation link. Names the active
 * channels and gives a one-click unsubscribe link for each one separately.
 * The Sunday-digest framing is intentionally honest about timing: the digest
 * delivery pipeline ships in a follow-up PR, so we don't promise a date here.
 */
export default function SubscriptionWelcomeEmail({
  channels,
  unsubUrls,
  unsubAllUrl,
  name,
}: Props) {
  const subject = "You're subscribed to NAISI";
  const hasNewsletter = channels.includes("newsletter");
  const hasEvents = channels.includes("events");
  const otherChannels = channels.filter(
    (c) => c !== "newsletter" && c !== "events",
  );
  const trimmedName = name?.trim();
  const greetingName = trimmedName ? trimmedName : "there";

  return (
    <EmailChrome
      subject={subject}
      preheader="What to expect, and how to unsubscribe at any time."
    >
      <Text style={{ fontSize: 16, lineHeight: 1.6, margin: "0 0 12px" }}>
        Hi {greetingName},
      </Text>
      <Text style={{ fontSize: 16, lineHeight: 1.6, margin: "0 0 16px" }}>
        Thanks for confirming. You&apos;re subscribed to:
      </Text>
      {hasNewsletter ? (
        <Text style={{ fontSize: 15, lineHeight: 1.6, margin: "0 0 12px" }}>
          <strong>The newsletter.</strong> A round-up of what&apos;s moving in
          AI safety, with three to five things worth reading and any
          opportunities you can act on.{" "}
          {unsubUrls.newsletter ? (
            <Link href={unsubUrls.newsletter} style={emailLinkStyle}>
              Unsubscribe
            </Link>
          ) : null}
        </Text>
      ) : null}
      {hasEvents ? (
        <Text style={{ fontSize: 15, lineHeight: 1.6, margin: "0 0 12px" }}>
          <strong>Event announcements.</strong> A heads-up when we run
          something on campus: talks, socials, workshops, reading sessions.{" "}
          {unsubUrls.events ? (
            <Link href={unsubUrls.events} style={emailLinkStyle}>
              Unsubscribe
            </Link>
          ) : null}
        </Text>
      ) : null}
      {otherChannels.map((c) => (
        <Text
          key={c}
          style={{ fontSize: 15, lineHeight: 1.6, margin: "0 0 12px" }}
        >
          <strong>{capitalise(channelLabel(c))}.</strong>{" "}
          {unsubUrls[c] ? (
            <Link href={unsubUrls[c]} style={emailLinkStyle}>
              Unsubscribe
            </Link>
          ) : null}
        </Text>
      ))}
      <Text style={{ fontSize: 15, lineHeight: 1.6, margin: "16px 0 12px" }}>
        Bookmark{" "}
        <Link href="https://naisi.uk" style={emailLinkStyle}>
          naisi.uk
        </Link>{" "}
        if you want to apply for the fellowship or browse what we&apos;ve
        published.
      </Text>
      <Text style={emailFooterTextStyle}>
        Every email we send carries a one-click unsubscribe header, so you can
        also drop these from your inbox UI directly.
        {unsubAllUrl ? (
          <>
            {" "}
            Or{" "}
            <Link href={unsubAllUrl} style={emailLinkStyle}>
              unsubscribe from everything at once
            </Link>
            .
          </>
        ) : null}
      </Text>
    </EmailChrome>
  );
}

function capitalise(s: string): string {
  if (!s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}
